# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{redis-lock}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Patrick Tulskie"]
  s.date = %q{2011-01-16}
  s.description = <<-DESC
  Adds pessimistic locking capabilities to the redis gem.
  
  Since these capabilities are utilized client-side, all clients must use this gem and follow the order of lock => make changes => unlock in order to obtain maximum safety when modifying sensitive keys.
  
  Tested with redis-server 2.0.4 and should work with all versions > 0.091.
  DESC
  s.email = %q{patricktulskie@gmail.com}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "README.md",
     "Rakefile",
     "VERSION",
     "lib/redis-lock.rb",
     "lib/redis/lock.rb",
     "spec/redis_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/PatrickTulskie/redis-lock}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.4.1}
  s.summary = %q{Adds the ability to utilize client-side pessimistic locking in Redis.}
  s.test_files = [
    "spec/redis_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.add_dependency "redis"
end

